### ISSUE TITLE
idea in gitignore

### ISSUE THREAD

**Issue by teploff** [sergey-sukharev/clipoid#1]
Dude, pls, add idea private directory in your gitignore

**Comment by sergey-sukharev** [comment]
@teploff **bruh**, gitignore already has this directory exclude important files there.

**Comment by teploff** [comment]
But it's not true!
![image](https://user-images.githubusercontent.com/17297772/114197041-a3d9d300-995a-11eb-9d64-a566c3e355ce.png)

**Comment by sergey-sukharev** [comment]
> But it's not true!
> ![image](https://user-images.githubusercontent.com/17297772/114197041-a3d9d300-995a-11eb-9d64-a566c3e355ce.png)

Look at this article https://habr.com/ru/post/421877/ . You can think that .idea folder in git, it's so bad move. But what i can else? So i can store important files for develop in cloud. But it's not 'gibko' and little more similar with KGK style, you know.
